nutanix:
- name: example_source_66
  base_url: https://nutanix.example.com:9440
  credential_id: example_source_67
  proxy_feature: nutanix_api
  verify_ssl: false
  api_limit: 500
  request_delay: 0.5
- name: example_source_68
  base_url: https://nutanix-dr.example.com:9440
  credential_id: example_source_69
  proxy_feature: nutanix_api
  verify_ssl: false
  api_limit: 500
  request_delay: 0.5
- name: example_source_70
  base_url: https://nutanix-c.example.com:9440
  credential_id: example_source_71
  proxy_feature: nutanix_api
  verify_ssl: false
  api_limit: 500
  request_delay: 0.5
vmware:
- name: example_source_72
  host: vcenter.example.com
  credential_id: example_source_73
  proxy_feature: vmware_api
  port: 443
  verify_ssl: false
  host_type: vcenter
- name: example_source_74
  host: example_source_37-01.example.com
  credential_id: example_source_75
  proxy_feature: vmware_api
  port: 443
  verify_ssl: false
  host_type: esxi
- name: example_source_76
  host: vcenter-b.example.com
  credential_id: example_source_77
  proxy_feature: vmware_api
  port: 443
  verify_ssl: false
  host_type: vcenter
